### PR TITLE
Fix Method equalitiy

### LINKED ISSUE #3118: undefined method `block_env' on an instance of Rubinius::CompiledCode
```
E, [2014-08-30T21:15:55.601407 #75353] ERROR -- : undefined method `block_env' on an instance of Rubinius::CompiledCode. (NoMethodError)                                                       
kernel/delta/kernel.rb:78:in `block_env (method_missing)'                                                                                                                                      
kernel/common/block_environment.rb:114:in `=='                                                                                                                                                 
kernel/common/method.rb:41:in `=='                                                                                                                                                             
/home/ghazel/.rvm/gems/rbx-2.2.10/gems/rainbows-4.6.2/lib/rainbows/http_server.rb:45:in `worker_loop'                                                                                      
kernel/common/method.rb:71:in `call'                                                                                                                                                           
/home/ghazel/.rvm/gems/rbx-2.2.10/gems/newrelic_rpm-3.9.3.241/lib/new_relic/agent/instrumentation/rainbows_instrumentation.rb:22:in `__script__'                                           
/home/ghazel/.rvm/gems/rbx-2.2.10/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:525:in `spawn_missing_workers'                                                                             
/home/ghazel/.rvm/gems/rbx-2.2.10/gems/rainbows-4.6.2/lib/rainbows/http_server.rb:61:in `spawn_missing_workers'                                                                            
/home/ghazel/.rvm/gems/rbx-2.2.10/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:536:in `maintain_worker_count'                                                                             
/home/ghazel/.rvm/gems/rbx-2.2.10/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:294:in `join'                                                                                              
/home/ghazel/.rvm/gems/rbx-2.2.10/gems/rainbows-4.6.2/bin/rainbows:127:in `__script__'                                                                                                     
kernel/common/kernel.rb:447:in `load'                                                                                                                                                          
/home/ghazel/.rvm/gems/rbx-2.2.10/bin/rainbows:23:in `__script__'                                                                                                                          
kernel/common/block_environment.rb:53:in `call_on_instance'                                                                                                                                    
kernel/common/eval.rb:176:in `eval'                                                                                                                                                            
/home/ghazel/.rvm/gems/rbx-2.2.10/bin/ruby_executable_hooks:15:in `__script__'                                                                                                             
kernel/delta/code_loader.rb:66:in `load_script'                                                                                                                                                
kernel/delta/code_loader.rb:152:in `load_script'                                                                                                                                               
kernel/loader.rb:649:in `script'                                                                                                                                                               
kernel/loader.rb:825:in `main'
```

### PR DESCRIPTION
**Pull request by tak1n**
A Method defined via def has an executable attribute of class Rubinius::CompiledCode. On the other site a method defined via define_method has an executable attribute of class Rubinius::BlockEnvironment::AsMethod.

Comparing method equality includes the comparison of executable equality.

For comparing an executable of type Rubinius::BlockEnvironment::AsMethod against an executable of Rubinius::CompiledCode results in an error because it tries to access the block_env attribute on an Rubinius::CompiledCode object, which doesn't exist.

This PR adds an early return like in Rubinius::CompiledCode#==

This closes #3118

### CODE REVIEW

File: spec/ruby/core/method/shared/eql.rb [hunk 1]
```diff
@@ -54,6 +54,16 @@
     @m_foo.send(@method, m2).should be_true
   end
 
+  it "returns false if comparing a method defined via define_method and def" do
+    MethodSpecs::Methods.send :define_method, :defined_foo, lambda {}
```
Comment (jemc) [inline spec/ruby/core/method/shared/eql.rb]: I think we should avoid modifying the fixtures from within the spec bodies.
It looks like `MethodSpecs::Methods` already has [some methods defined with `define_method`](https://github.com/rubinius/rubinius/blob/621953b6e6ea1e948de8e70ac3422a98f3a3c82f/spec/ruby/core/method/fixtures/classes.rb#L80-L85).  You could probably use one of those, or move your defined method to that file.

Comment (tak1n) [inline spec/ruby/core/method/shared/eql.rb]: True, just used it because it was used in the above spec example :)
I'll change it
