### PR TITLE
WIP: Fix range of Fixnum. Closes #3636.

### LINKED ISSUE #3636: Inconsistent class with negative integer constant
## Problem

`(-0x4000_0000_0000_0000).class` becomes Bignum, which can be stored in Fixnum.

Existing two representations for the same integer value may cause unexpected behaviors.
## How to Reproduce

``` rb
val = -0x4000_0000_0000_0000
p val.class # => Bignum (unexpected)
p (~~val).class #=> Fixnum (expected)
p val.equal?(~~val) # => false (unexpected)
```
## Configuration Details
- Output of `rbx -v`:
  `rubinius 3.27 (2.2.2 628fe1c2 2016-04-15 3.4.2) [x86_64-linux-gnu]` : installed from ruby-build & rbenv
- Output of `uname -a`:
  `Linux localhost.localdomain 3.10.0-327.10.1.el7.x86_64 #1 SMP Tue Feb 16 17:03:50 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
- Distribution name (in case of Linux/BSD): CentOS 7

### PR DESCRIPTION
**Pull request by brixen**

### CODE REVIEW

File: machine/include/capi/capi_oop.h [hunk 1]
```diff
@@ -98,8 +98,10 @@
...
 #define CAPI_TAG_FIXNUM(v)  ((VALUE)(((VALUE)(v) << TAG_FIXNUM_SHIFT) | TAG_FIXNUM))
 
-#define FIXNUM_WIDTH        ((8 * sizeof(native_int)) - TAG_FIXNUM_SHIFT - 1)
-#define FIXNUM_MAX          (((native_int)1 << FIXNUM_WIDTH) - 1)
-#define FIXNUM_MIN          (-(FIXNUM_MAX))
+#define FIXNUM_MAX_WIDTH ((8 * sizeof(native_int)) - TAG_FIXNUM_SHIFT - 1)
+#define FIXNUM_MIN_WIDTH (FIXNUM_MAX_WIDTH + 1)
+
+#define FIXNUM_MAX (((native_int)1 << FIXNUM_MAX_WIDTH) - 1)
+#define FIXNUM_MIN (-(FIXNUM_MAX) - 1)
```
Comment (sirbikealot) [inline machine/include/capi/capi_oop.h]: define FIXNUM_MIN (-1 - FIXNUM_MAX)

File: machine/oop.hpp [hunk 2]
```diff
@@ -58,17 +58,11 @@ namespace rubinius {
...
- * Bignum does not store negative numbers in twos-complement. Consequently,
- * this value of FIXNUM_MIN allows for checking that a value is in the Fixnum
- * range merely by checking a count of the bits used to represent the number.
- */
-#define FIXNUM_MIN   (-(FIXNUM_MAX))
+#define FIXNUM_MAX_WIDTH ((8 * sizeof(native_int)) - TAG_FIXNUM_SHIFT - 1)
+#define FIXNUM_MIN_WIDTH (FIXNUM_MAX_WIDTH + 1)
+
+#define FIXNUM_MAX (((native_int)1 << FIXNUM_MAX_WIDTH) - 1)
+#define FIXNUM_MIN (-(FIXNUM_MAX) - 1)
```
Comment (sirbikealot) [inline machine/oop.hpp]: define FIXNUM_MIN (-1 - FIXNUM_MAX)
